### PR TITLE
remove boost dependency

### PR DESCRIPTION
**Pull request by koide3**

### CODE REVIEW

**Comment by koide3** [comment]
Hi @Seekerzero ,
I'm trying to remove the dependency on boost and now testing this `noboost` branch. I tried to avoid API changes that require user-side changes, and now I want to see what happens in the user side. I would appreciate if you could see if this update causes any issues in  your environment.

**Comment by Seekerzero** [comment]
This should be a quick test, let me do it now.

**Comment by Seekerzero** [comment]
Hi @koide3,
I just successfully install the noboost branch on my end. The only issue I encounter was that the fmt lib version, the default version that Ubuntu 20.04 using is 6.1.2 and Iridescence requires 9.x.x. And I have made a pull request to edit the README.md. I will continue to follow up this version to check if there is any feature flaws.

**Comment by koide3** [comment]
@Seekerzero 
Thanks a lot! I'll check the fmt version issue. I'll try to make it compatible with the  old version of fmt. If you find other issues, please let me know. I'll merge this branch after doing further testing later.

**Comment by koide3** [comment]
Because fmt was used only in a few points, I decided to replace them with std functionalities and remove the dependency on fmt.

**Comment by Seekerzero** [comment]
Thanks! I will test it later tomorrow. Btw, I was mentioned that the default version for boost branch on ubuntu 20.04 is 1.71 and the version that you used for the filesystem was from 1.82. So actually remove boost from the dependency actually is a good decision :)

**Comment by Seekerzero** [comment]
Hi @koide3, this branch is tested on my side with no issue.

**Comment by koide3** [comment]
Thanks. I'm doing some tests, and for now, I've not found further issues. I think I will merge this in this week after checking a few more points.

**Comment by koide3** [comment]
@Seekerzero 
I updated the installation process so that the library can be linked to user programs without `FindIridescence.cmake` as follows. When you have time, could you see if it works on your side? After checking this, I'll merge this PR.

```cmake
# Find package
find_package(Iridescence REQUIRED)

# Add include dirs and link libraries
add_executable(your_program
  src/your_program.cpp
)
target_link_libraries(your_program
  Iridescence::Iridescence
)
```

**Comment by Seekerzero** [comment]
Sure，I will test it tonight.

**Comment by Seekerzero** [comment]
@koide3 
I just tested the installation on two related projects, both works! I think it is safe to merge it. Nice Job!

**Comment by koide3** [comment]
Great! Thanks a lot!

**Pull request merged**
