### PR TITLE
[wip] Fix examples

### PR DESCRIPTION
**Pull request by juliangaal**
This PR:

* fixes `example/ext_light_viewer_capture.cpp` and `example/ext_light_viewer_effects.cpp` segfault by wrapping the call to `nvidia-smi` in a try/catch block. This effectively makes these examples work on non-GPU systems.
* fixes `example/gl_test_field_example.cpp` by correctly (?) initializing the number of color buffers in `gl_canvas`. Please let me know if my thinking is correct here.
* removes some implicit conversions found with `-Wall`

Remaining Issues:
* Rendered text in `/ext_light_viewer_effects.cpp` and `example/ext_light_viewer_capture.cpp` is mangled/mixed like this
issue#1
* Bunny primitive selection in `example/gl_test_field_example.cpp` loads empty texture with warning: `warning: attrib vert_color not found`, even when correcting this typo:

  ```cpp
        const char* items[] = {.... "BUNNYY"};
        --> const char* items[] = {.... "BUNNY"};
  ```

### CODE REVIEW

**Comment by koide3** [comment]
Thanks for your PR. I'll check it in a few days.

**Comment by juliangaal** [comment]
I could create a PR into a different branch, like e.g. `dev`, to make it easier for you to get started.

**Comment by koide3** [comment]
Thanks. It would be nice if you could split the PR into three separated PRs so that I can quickly check and merge from easy ones.

**Comment by juliangaal** [comment]
Ah, ok. Let me take care of that in the beginning of next week. Have a nice weekend.

**Pull request closed without merging**
